version: "3.9"

services:
  frontend:
    image: drios8331/fronted:latest
    container_name: fronted
    expose:
      - "9000"
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: laravel_nginx
    ports:
      - "9000:80"
    depends_on:
      - frontend
    networks:
      - app_network

  backend:
    image: drios8331/backend:latest
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
